### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by iambigd** [jiangyoucai/vue-editor#1]
作者你好，我在使用你的範例時，在import後都會造成錯誤，有什麼重要的loader要安裝嗎?
我剛剛接觸webpack與vue，希望可以解答一下  
import WangEditor from 'wangeditor' 

node_modules/wangeditor/dist/css/wangEditor.css Unexpected token (7:0)
You may need an appropriate loader to handle this file type.
| /* 按钮颜色 */
| /* tab selected 状态下的颜色 */
| .wangEditor-container {
|   position: relative;
|   background-color: #fff;

**Comment by jiangyoucai** [comment]
make sure this in your webpack config
```
loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json'
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
```

or
you can use vue-cli,it will help you only run the command

**vue init webpack my-project**

here is the link [http://cn.vuejs.org/v2/guide/installation.html](url)

**Comment by iambigd** [comment]
感謝提示，已經可以work了
