### ISSUE TITLE
跨域上传图片出错

### ISSUE THREAD

**Issue by lanbaba** [jiangyoucai/vue-editor#4]
跨域上传文件到阿里云时出错：
XMLHttpRequest cannot load http://tjdesigner.oss-cn-shanghai.aliyuncs.com/. Response to preflight request doesn't pass access control check: A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:8080' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.
看wangeditor官方issue，说要去源码中修改 xhr.withCredentials = true; 改成 false 就没有跨域问题了。
能否配置一个简单参数？

**Comment by jiangyoucai** [comment]
不仅上传图片
rest api 发出跨域请求，像post，put，delete，options
同样也会出这个错

解决跨域问题，最优方案

**修改后端配置**

一段golang代码，仅供参考

```
w.Header().Set("Access-Control-Allow-Origin", "*")
w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
```

**Comment by lanbaba** [comment]
谢谢提供的解决方案，关键是我打算浏览器直传阿里云，不经过我们自己的的服务器，所以服务器返回的Header无法控制，只能修改客户端代码。
阿里云oss返回Header：
Access-Control-Allow-Methods:GET, POST, PUT, DELETE, HEAD
Access-Control-Allow-Origin:*

**Comment by lanbaba** [comment]
阿里云服务器端可配置限定域名上传
