### ISSUE TITLE
求救火，哥们，能再这个的基础上增加基于plupload自定义上传吗？

### ISSUE THREAD

**Issue by hasbug** [jiangyoucai/vue-editor#6]
我用了你的这个，可以用。然后我根据wangeditor官网的自定义plupload来自定义上传，但发现，点击上传处并没有弹出选择文件的框。查看html发现并未生成对应的input上传表单。
求帮忙，项目急着上线了。谢谢。

**Comment by jiangyoucai** [comment]
建议配置uploadURL: '/api/v1/help/upload/wangEditorH5File'路径
使用后端处理图片上传
