### ISSUE TITLE
在使用wangeditor2时的错误

### ISSUE THREAD

**Issue by VenusPP** [jiangyoucai/vue-editor#7]
我用wangeditor2上传图片时，页面加载不出来图片并报错（内容如下）。请问如何解决？

wangEditor.js?2929:3073 wangEditor提示: 使用返回的结果获取图片，发生错误。请确认以下结果是否正确：<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /api/v1/help/upload/wangEditorH5File</pre>
</body>
</html>

**Comment by jiangyoucai** [comment]
```
/api/v1/help/upload/wangEditorH5File
```
示例地址，仅供参考
上传图片的接口，请联系后端实现

**Comment by VenusPP** [comment]
谢谢  看了下文档 问题已解决了
